[package]
name = "wordle-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fst = { version = "0.4.7"}
regex-automata = { version = "0.1.9", features = ["transducer"] }
dialoguer = "*"
regex = "*"
